// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxh5oIDj-GKFToJ1WBXSdXODuI-M_4fb0',
    appId: '1:386104742233:web:1377f92e8a786020dc7c48',
    messagingSenderId: '386104742233',
    projectId: 'clonespotify-1b7f1',
    authDomain: 'clonespotify-1b7f1.firebaseapp.com',
    storageBucket: 'clonespotify-1b7f1.appspot.com',
    measurementId: 'G-RQTDHTMTMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeD1cI_PG9Dxg8GeGIQ2-iP_w1ggJ7ADQ',
    appId: '1:386104742233:android:bd8c29f689cc22f3dc7c48',
    messagingSenderId: '386104742233',
    projectId: 'clonespotify-1b7f1',
    storageBucket: 'clonespotify-1b7f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiCbQ6NwFv_ruHc0_u0OIR79CcwcINsWE',
    appId: '1:386104742233:ios:bc2499a1ba334f37dc7c48',
    messagingSenderId: '386104742233',
    projectId: 'clonespotify-1b7f1',
    storageBucket: 'clonespotify-1b7f1.appspot.com',
    iosBundleId: 'com.example.spotifyProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiCbQ6NwFv_ruHc0_u0OIR79CcwcINsWE',
    appId: '1:386104742233:ios:bc2499a1ba334f37dc7c48',
    messagingSenderId: '386104742233',
    projectId: 'clonespotify-1b7f1',
    storageBucket: 'clonespotify-1b7f1.appspot.com',
    iosBundleId: 'com.example.spotifyProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxh5oIDj-GKFToJ1WBXSdXODuI-M_4fb0',
    appId: '1:386104742233:web:f59341502b2d4e40dc7c48',
    messagingSenderId: '386104742233',
    projectId: 'clonespotify-1b7f1',
    authDomain: 'clonespotify-1b7f1.firebaseapp.com',
    storageBucket: 'clonespotify-1b7f1.appspot.com',
    measurementId: 'G-7559T3BT9M',
  );
}
